INSERT INTO user (username, password, display_name)
VALUES ('JasonK97', 'jasonkent', 'Jason Kent');

INSERT INTO character (character_name,
                    class,
                    character_level,
                    race,
                    alignment,
                    strength,
                    dexterity,
                    constitution,
                    intelligence,
                    wisdom,
                    charisma,
                    maxHP,
                    accessible_items,
                    currency,
                    feats,
                    features)
            VALUES ('Jalsonio',
                    'Fighter',
                    '1',
                    'Half-Elf',
                    'Lawful Good',
                    '16',
                    '14',
                    '13',
                    '11',
                    '10',
                    '12',
                    '15',
                    'Sword, Shield, Armor',
                    '150gp',
                    'Armor Proficiency (Chainmail)',
                    'Male, Tall, Thin, Strong');